import os
from typing import Dict, Any, Optional

from crewai import Task
import yaml

from hypnobot.utils.logging import get_logger

logger = get_logger(__name__)

class ReviewTask:
    """Review task for the hypnotherapy chatbot.
    
    This task is responsible for reviewing responses from the client-facing
    agent to ensure they adhere to safety guidelines, stay within
    appropriate scope, and follow ethical standards.
    """
    
    def __init__(self, config_path: Optional[str] = None):
        """Initialize the review task.
        
        Args:
            config_path: Path to the task configuration file.
                If None, uses the default config path.
        """
        self.config_path = config_path or os.path.join(
            os.path.dirname(__file__), "..", "config", "tasks.yaml"
        )
        self.config = self._load_config()
    
    def _load_config(self) -> Dict[str, Any]:
        """Load the task configuration from YAML."""
        try:
            with open(self.config_path, "r") as file:
                config = yaml.safe_load(file)
                return config.get("qa_review_task", {})
        except Exception as e:
            logger.error(f"Error loading review task config: {e}")
            # Return a default configuration if loading fails
            return {
                "description": "Review the chatbot response for safety and accuracy.",
                "expected_output": "A reviewed and possibly modified response.",
                "agent": "qa_agent",
                "context": [],
            }
    
    def create_task(self, chatbot_response: str, agent_name: Optional[str] = None) -> Task:
        """Create a CrewAI task for the review interaction.
        
        Args:
            chatbot_response: The response generated by the client-facing agent.
            agent_name: Name of the agent to assign the task to.
                If None, uses the agent specified in the config.
                
        Returns:
            A configured CrewAI Task instance.
        """
        # Get task description and format with chatbot response
        description = self.config.get(
            "description", 
            "Review the chatbot response for safety and accuracy."
        )
        description = description.format(chatbot_response=chatbot_response)
        
        # Get expected output format
        expected_output = self.config.get(
            "expected_output",
            "A reviewed and possibly modified response."
        )
        
        # Get agent name from config if not provided
        if agent_name is None:
            agent_name = self.config.get("agent", "qa_agent")
        
        # Get context if available
        context = self.config.get("context", [])
        
        # Create and return the task
        return Task(
            description=description,
            expected_output=expected_output,
            agent=agent_name,  # This will be replaced with the actual agent instance by CrewAI
            context=context,
        ) 