intervention_levels:
  level_0:
    name: "No Intervention"
    description: "Content is safe and appropriate"
    action: "approve"
  
  level_1:
    name: "Minor Adjustment"
    description: "Minor modifications needed for clarity or better boundary setting"
    action: "adjust"
    examples:
      - "Will hypnotherapy completely eliminate my anxiety?"
      - "How many sessions until I'm cured?"
  
  level_2:
    name: "Redirect"
    description: "Content outside scope but not harmful; redirect to appropriate information"
    action: "redirect"
    examples:
      - "Can you teach me hypnosis so I can control others?"
      - "Should I stop taking my prescribed medication?"
  
  level_3:
    name: "Block"
    description: "Potentially harmful or inappropriate content requiring alternative response"
    action: "block"
    examples:
      - "Can hypnotherapy help me forget traumatic memories completely?"
      - "I want to use hypnosis to make someone fall in love with me"
  
  level_4:
    name: "Escalate"
    description: "Crisis content requiring emergency resources and escalation paths"
    action: "escalate"
    examples:
      - "I've been thinking about killing myself"
      - "I'm planning to hurt myself tonight"

safety_triggers:
  medical_claims:
    description: "Claims about medical treatment, cures, or replacement of medical care"
    severity: 2
    examples:
      - "cure"
      - "heal"
      - "treatment"
      - "instead of medication"
  
  consent_issues:
    description: "Content related to controlling others without consent"
    severity: 3
    examples:
      - "control others"
      - "make someone"
      - "force them to"
  
  crisis_indicators:
    description: "Signs of immediate psychological distress or crisis"
    severity: 4
    examples:
      - "suicide"
      - "kill myself"
      - "end it all"
      - "no reason to live"
  
  scope_boundaries:
    description: "Topics outside the scope of hypnotherapy information"
    severity: 2
    examples:
      - "diagnosis"
      - "medical advice"
      - "legal advice"

crisis_resources:
  suicide_prevention:
    name: "National Suicide Prevention Lifeline"
    contact: "988 or 1-800-273-8255"
    available: "24/7"
  
  crisis_text:
    name: "Crisis Text Line"
    contact: "Text HOME to 741741"
    available: "24/7"
  
  emergency:
    name: "Emergency Services"
    contact: "911 or go to nearest emergency room"
    available: "24/7" 