categorization_task:
  agent: categorizer
  description: >
    Classify the inquiry. If it's unsafe, off-topic, or a medical emergency, mark it as such.
    Otherwise, pass it through as APPROPRIATE.

    Inquiry:
    {user_input}
  expected_output: >
    One of: APPROPRIATE, INAPPROPRIATE, MEDICAL_REFERRAL, TROLLING
    + One-sentence rationale.

initial_response_task:
  agent: support_agent
  description: >
    Generate a warm and informative response to the user's hypnotherapy-related question.
    Use only verified methods from the practice.

    Inquiry:
    {user_input}

    Categorization:
    {categorization_task.output}
  expected_output: >
    A 1–4 paragraph informative response, accurate to practice methodology.

safety_check_task:
  agent: safety_officer
  description: >
    Review the assistant's response to remove or correct anything that may be misleading,
    unethical, medically inappropriate, or risky.

    Original Inquiry:
    {user_input}

    Draft Response:
    {initial_response_task.output}
  expected_output: >
    A cleaned and ethically sound response.

writing_improvement_task:
  agent: writing_coach
  description: >
    Refine the response for tone, empathy, and writing quality.

    Original Inquiry:
    {user_input}

    Safety-Checked Response:
    {safety_check_task.output}
  expected_output: >
    A rewritten version that flows well and sounds professional and caring.

accessibility_task:
  agent: accessibility_agent
  description: >
    Adjust the message to be understandable by the general public,
    at a high school reading level or below, without losing key meaning.

    Original Inquiry:
    {user_input}

    Improved Response:
    {writing_improvement_task.output}
  expected_output: >
    A final version that is simple, kind, and easy to grasp.
