categorization_task:
  agent: categorizer
  description: >
    Determine if the question is appropriate, safe, and related to hypnotherapy.
    Inquiry: {user_input}
  expected_output: >
    One of: APPROPRIATE, INAPPROPRIATE, MEDICAL_REFERRAL, TROLLING + One-sentence explanation.

initial_response_task:
  agent: support_agent
  description: >
    Generate a warm and helpful response to the user's question.
    Inquiry: {user_input}
    Categorization: {categorization_task.output}
  expected_output: >
    1–4 paragraph response relevant to hypnotherapy best practices.

safety_check_task:
  agent: safety_officer
  description: >
    Review the assistant's draft and fix any unsafe or misleading advice.
    Draft Response: {initial_response_task.output}
  expected_output: >
    Ethically sound and safe response.

writing_improvement_task:
  agent: writing_coach
  description: >
    Rewrite the response for tone and professionalism.
    Safety Checked Response: {safety_check_task.output}
  expected_output: >
    Clear and emotionally engaging final draft.

accessibility_task:
  agent: accessibility_agent
  description: >
    Make the response easy to understand for a general audience.
    Improved Response: {writing_improvement_task.output}
  expected_output: >
    Final simplified version at a high school reading level.
