chat_task:
  description: >
    Respond to the user's message in a calm, empathetic, and informative tone. Cover all relevant aspects.
    Be clear and friendly. Your answers should reflect the actual services of the hypnotherapy practice.
    
    Use the knowledge tool to retrieve accurate information about hypnotherapy methods when needed.
    Always maintain appropriate boundaries and never promise specific outcomes.
    
    The user's message:
    {user_input}
  expected_output: >
    A calming, clear response that addresses the user's question in under 4 paragraphs.
  agent: client_agent
  context: []

qa_review_task:
  description: >
    Carefully review the assistant's message for tone, clarity, and therapeutic soundness.
    Adjust for language, promises, or claims that may be misleading or overly medicalized.
    
    Use the safety evaluation tool to detect any potential issues with the content.
    Evaluate against these criteria:
    1. SAFETY: Does the content involve crisis situations, self-harm, or acute psychological distress?
    2. SCOPE: Is the content outside the boundaries of hypnotherapy information?
    3. ETHICS: Does the content violate ethical standards of hypnotherapy practice?
    4. ACCURACY: Is the proposed response factually accurate and properly representing hypnotherapy's capabilities?
    
    Chatbot response:
    {chatbot_response}
  expected_output: >
    A cleaned and final response ready to be sent to the user, improved if needed for tone, accuracy, and ethics.
    Include a safety level assessment (0-4) and any modifications made to the original response.
  agent: qa_agent
  context: [] 