hypnotherapy_inquiry:
  description: >
    {user_name} has asked the following about hypnotherapy:
    "{user_message}"

    Provide a simple, easy-to-understand response about hypnotherapy that answers
    their question. Use everyday language at a 7-8th grade reading level. Keep your
    answer brief (3-5 short paragraphs maximum) and friendly, as if you're talking
    to a friend.

    Avoid technical terms, long explanations, and academic language. Use short
    sentences and common words. Be supportive while still being accurate.

    If the question involves a crisis situation, mental health emergency,
    or serious medical condition, provide a simple referral to professional help.
  expected_output: >
    A brief, friendly response in simple language (7-8th grade level) that directly
    answers the question. Keep to 3-5 short paragraphs maximum. Use everyday words
    and avoid technical terms or complex explanations.

    Sound conversational, like a knowledgeable friend giving advice, not like 
    a textbook or academic paper.
  agent: "hypnotherapy_guide"
  tools: []

safety_review:
  description: >
    Review the response provided to {user_name}'s inquiry about hypnotherapy.
    The original inquiry was: "{user_message}"
    
    The proposed response is:
    "{hypnotherapy_response}"

    Evaluate this response against these criteria:
    1. SAFETY: Does it address crisis situations appropriately? Does it avoid harmful suggestions?
    2. SCOPE: Does it stay within appropriate boundaries?
    3. ETHICS: Does it avoid promising specific outcomes?
    4. SIMPLICITY: Is it written in simple language a 7-8th grader could understand?
    5. BREVITY: Is it brief (3-5 short paragraphs maximum)?
    
    If the response is too long, too complex, or uses technical language, rewrite it
    to be simpler, shorter, and more conversational while keeping the key points.
  expected_output: >
    Provide your assessment with the following structure:

    Safety Level Assessment: [0-4] 
    (0: safe, 1: minor concerns, 2: moderate concerns, 3: significant concerns, 4: unsafe)

    The assistant's response after review is: "[Insert revised response here, or original if no changes needed. Remember to keep it simple, brief, and at 7-8th grade level]"

    Modifications: [Describe any changes made to the original response, or "None needed" if no changes]

    Reasoning: [Brief explanation of your assessment and any modifications]
  agent: "safety_specialist"
  tools: [] 